#################### execute in RedHat 6 ####################

- name: execute in RedHat 6
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version in ["6"]
  block:
  - name: TWGCB-01-003-0092 /boot/grub/grub.conf
    become: true
    file:
      path: /boot/grub/grub.conf
      mode: '0600' # TWGCB-01-003-0092
      owner: root # TWGCB-01-003-0094
      group: root # TWGCB-01-003-0093

#################### execute in RedHat older 8 ####################

- name: execute in RedHat older 8
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version | int >= 8
  block:
  - name: execute command
    command: "{{ item }}"
    with_items:
    - useradd -D -f 30 # TWGCB-01-008-0228
    - usermod -g 0 root # root帳號所屬群組: TWGCB-01-008-0240

  - name: 更新system-auth與password-auth檔案 TWGCB-01-008-0209
    shell: |
      #!/bin/bash
      CP=$(authselect current | awk 'NR == 1 {print $3}' | grep custom/)
      for FN in system-auth password-auth; do
          [[ -n $CP ]] && PTF=/etc/authselect/$CP/$FN || PTF=/etc/authselect/$FN
          [[ -z $(grep -E '^\s*password\s+requisite\s+pam_pwquality.so\s+.*enforce_for_root\s*.*$' $PTF) ]] && sed -ri 's/^\s*(password\s+requisite\s+pam_pwquality.so\s+)(.*)$/\1\2 enforce_for_root/' $PTF
      done
      authselect apply-changes
  - name: 更新system-auth檔案 TWGCB-01-008-0222
    shell: |
      #!/bin/bash
      CP=$(authselect current | awk 'NR == 1 {print $3}' | grep custom/)
          [[ -n $CP ]] && PTF=/etc/authselect/$CP/system-auth || PTF=/etc/authselect/system-auth
          [[ -n $(grep -E '^\s*password\s+(sufficient\s+pam_unix|requi(red|site)\s+pam_pwhistory).so\s+([^#]+\s+)*remember=\S+\s*.*$' $PTF) ]] && sed -ri 's/^\s*(password\s+(requisite|sufficient)\s+(pam_pwquality\.so|pam_unix\.so)\s+)(.*)(remember=\S+\s*)(.*)$/\1\4 remember=3 \6/' $PTF || sed -ri 's/^\s*(password\s+(requisite|sufficient)\s+(pam_pwquality\.so|pam_unix\.so)\s+)(.*)$/\1\4 remember=3/' $PTF
      authselect apply-changes

  - name: 更新system-auth與password-auth檔案 TWGCB-01-008-0224
    shell: |
      #!/bin/bash
      CP=$(authselect current | awk 'NR == 1 {print $3}' | grep custom/)
      for FN in system-auth password-auth; do
      [[ -n $CP ]] && PTF=/etc/authselect/$CP/$FN || PTF=/etc/authselect/$FN
      [[ -z $(grep -E '^\s*password\s+sufficient\s+pam_unix.so\s+.*sha512\s*.*$' $PTF) ]] && sed -ri 's/^\s*(password\s+sufficient\s+pam_unix.so\s+)(.*)$/\1\2 sha512/' $PTF
      done
      authselect apply-changes
  - name: 系統帳號登入方式 TWGCB-01-008-0237
    shell: |
      #!/bin/bash
      awk -F: '($1!="root" && $1!~/^\+/ && $3<'"$(awk '/^\s*UID_MIN/{print $2}' /etc/login.defs)"') {print $1}' /etc/passwd | xargs -I '{}' passwd -S '{}' | awk '($2!="L" && $2!="LK") {print $1}' | while read user; do usermod -L $user; done