
- name: /etc/profile.d/tmout.sh
  template:
    owner: root
    group: root
    mode: 0644
    dest: /etc/profile.d/tmout.sh
    src: tmout.sh

- name: /etc/csh.cshrc
  template:
    owner: root
    group: root
    mode: 0644
    dest: /etc/csh.cshrc
    src: "{{csh_cshrc}}"
- name: /etc/login.defs
  template:
    owner: root
    group: root
    mode: 0644
    dest: /etc/login.defs
    src: "{{login_defs}}"



#################### execute in RedHat 7 ####################

- name: execute in RedHat 7
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version in ["7"]
  block:
  - name: /etc/securetty RedHat7 TWGCB-01-003-0059,TWGCB-01-003-0060,TWGCB-01-003-0061,TWGCB-01-003-0062
    template:
      owner: root
      group: root
      mode: 0600
      dest: /etc/securetty
      src: TWGCB-003-securetty-RedHat7
  - name: /etc/pam.d/su
    template:
      owner: root
      group: root
      mode: 0644
      dest: /etc/pam.d/su
      src: "{{su}}"
  - name: /etc/sudoers in RedHat 7
    template:
      owner: root
      group: root
      mode: 0640
      dest: /etc/sudoers
      src: TWGCB-003-sudoers-RedHat7
  - name: /etc/sysconfig/init in RedHat 7
    template:
      owner: root
      group: root
      mode: 0644
      dest: /etc/sysconfig/init
      src: "{{init_RedHat7}}"
  - name: /etc/profile in RedHat 7
    template:
      owner: root
      group: root
      mode: 0644
      dest: /etc/profile
      src: "{{profile_redHat_7}}"
  - name: /etc/issue in RedHat 7
    template:
      owner: root
      group: root
      mode: 0644
      dest: /etc/issue
      src: issue-RedHat7

#################### execute in RedHat 5 6 ####################

- name: execute in RedHat 5 6
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version in ["5","6"]
  block:
  - name: /etc/securetty RedHat6 TWGCB-01-003-0059,TWGCB-01-003-0060,TWGCB-01-003-0061,TWGCB-01-003-0062
    template:
      owner: root
      group: root
      mode: 0600
      dest: /etc/securetty
      src: TWGCB-003-securetty-RedHat6
  - name: /etc/profile in RedHat 5,6
    template:
      owner: root
      group: root
      mode: 0644
      dest: /etc/profile
      src: "{{profile_redHat_6}}"
  - name: /etc/sudoers in RedHat 5,6
    template:
      owner: root
      group: root
      mode: 0640
      dest: /etc/sudoers
      src: TWGCB-003-sudoers-RedHat6
  - name: /etc/issue in RedHat 5,6
    template:
      owner: root
      group: root
      mode: 0644
      dest: /etc/issue
      src: issue-RedHat6

#################### execute in RedHat 5 6 7 ####################

- name: execute in RedHat 5,6,7
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version in ["5","6","7"]
  block:

  - name: /etc/bashrc
    template:
      owner: root
      group: root
      mode: 0644
      dest: /etc/bashrc
      src: "{{bashrc}}"

  - name: /etc/pam.d/system-auth
    template:
      owner: root
      group: root
      mode: 0644
      dest: /etc/pam.d/system-auth
      src: system-auth

  - name: /etc/default/useradd
    template:
      owner: root
      group: root
      mode: 0600
      dest: /etc/default/useradd
      src: TWGCB-003-useradd

  - name: /etc/profile.d/autologout.csh
    template:
      owner: root
      group: root
      mode: 0644
      dest: /etc/profile.d/autologout.csh
      src: TWGCB-003-autologout.csh

  - name: /etc/sysconfig/init in RedHat 5,6
    template:
      owner: root
      group: root
      mode: 0644
      dest: /etc/sysconfig/init
      src: init-RedHat6
  - name: /etc/libuser.conf
    template:
      owner: root
      group: root
      mode: 0644
      dest: /etc/libuser.conf
      src: libuser.conf


#################### execute in RedHat older 8 ####################

- name: execute in RedHat older 8
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version | int >= 8
  block:

  - name: /etc/security/pwquality.conf
    template:
      owner: root
      group: root
      mode: 0644
      dest: /etc/security/pwquality.conf
      src: "{{pwquality_redhat_8_conf}}"

  - name: /etc/security/faillock.conf
    template:
      owner: root
      group: root
      mode: 0644
      dest: /etc/security/faillock.conf
      src: "{{faillock_redhat_8_conf}}"
  - name: /etc/pam.d/postlogin
    template:
      owner: root
      group: root
      mode: 0644
      dest: /etc/pam.d/postlogin
      src: "{{postlogin_redhat_8}}"
  - name: /etc/profile
    template:
      owner: root
      group: root
      mode: 0644
      dest: /etc/profile
      src: "{{profile_redHat_8}}"
  - name: /etc/bashrc
    template:
      owner: root
      group: root
      mode: 0644
      dest: /etc/bashrc
      src: "{{bashrc_redHat_8}}"
  - name: /etc/pam.d/su
    template:
      owner: root
      group: root
      mode: 0644
      dest: /etc/pam.d/su
      src: "{{su_redHat_8}}"


