
#################### execute in RedHat older 8 ####################

- name: execute in RedHat older 8
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version | int >= 8
  block:
  - name: 定期檢查檔案系統完整性
    cron:
      user: root
      name: 定期檢查檔案系統完整性(TWGCB-01-008-0037, TWGCB-01-012-0037)
      minute: 0 
      hour: 5
      job: /usr/sbin/aide --check