# TWGCB 檢查腳本

- name: RedHat Base version 8
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version | int >= 8
  block:
  
  - name: execute command
    command: "{{ item }}"
    with_items: 
    - find -L /bin /sbin /usr/bin /usr/sbin /usr/local/bin /usr/local/sbin -perm /0022 -exec ls -l {}\; # TWGCB-01-008-0066
    - find -L /bin /sbin /usr/bin /usr/sbin /usr/local/bin /usr/local/sbin ! -user root -exec ls -l {}\; # TWGCB-01-008-0067
    - find -L /bin /sbin /usr/bin /usr/sbin /usr/local/bin /usr/local/sbin ! -group root ! -group tty ! -group slocate ! -group lock -exec ls -l {}\; # TWGCB-01-008-0068
    - find -L /lib /lib64 /usr/lib /usr/lib64 -perm /0022 -type f -exec ls -l {}\; # TWGCB-01-008-0069
    - find -L /lib /lib64 /usr/lib /usr/lib64 ! -user root -exec ls -l {}\; # TWGCB-01-008-0070
    - find -L /lib /lib64 /usr/lib /usr/lib64 ! -group root -exec ls -l {}\; # TWGCB-01-008-0071
    - grep '^\+:' /etc/passwd # TWGCB-01-008-0075
    - grep '^\+:' /etc/shadow # TWGCB-01-008-0076
    - grep '^\+:' /etc/group # TWGCB-01-008-0077
    - "awk -F: '($3 == 0) { print $1 }' /etc/passwd" # TWGCB-01-008-0078
    - ip link | grep -i promisc # 網路介面混雜模式: TWGCB-01-008-0131, TWGCB-01-012-0131
    - grep -iw log_file /etc/audit/auditd.conf # 尋找稽核日誌目錄: TWGCB-01-008-0137,TWGCB-01-008-0138,TWGCB-01-008-0139,TWGCB-01-008-0140, TWGCB-01-012-0137, TWGCB-01-012-0138, TWGCB-01-012-0139
    - stat -c "%a %n" /sbin/auditctl /sbin/aureport /sbin/ausearch /sbin/autrace /sbin/auditd /sbin/audisp-remote /sbin/audisp-syslog /sbin/augenrules /sbin/rsyslogd 2>/dev/null | grep 755 # 稽核工具權限: TWGCB-01-008-0143, TWGCB-01-012-0143, TWGCB-01-008-0144, TWGCB-01-012-0144
    - ps -eZf | grep unconfined_service_t | grep -v grep # 未受限程序: TWGCB-01-008-0189, TWGCB-01-012-0187
    - grep cron /etc/rsyslog.conf /etc/rsyslog.d/*.conf # TWGCB-01-008-0207
    - find / -name shosts.equiv # shosts.equiv檔案: TWGCB-01-008-0290, TWGCB-01-012-0282
    - find / -name '*.shosts' # .shosts檔案: TWGCB-01-008-0291, TWGCB-01-012-0283
    - grep -i '(nopasswd|!authenticate)' /etc/sudoers /etc/sudoers.d/* # 要求使用者必須經過身分驗證才能提升權限: TWGCB-01-008-0231, TWGCB-01-012-0229
    
  
  - name: 使用者家目錄權限(TWGCB-01-008-0079, TWGCB-01-012-0079)
    shell: |
      #!/bin/bash
      grep -E -v '^(halt|sync|shutdown)' /etc/passwd | awk -F: '($7 != "/sbin/nologin" && $7 != "/bin/false") { print $1 " " $6 }' | while read user dir; do
        if [ ! -d "$dir" ]; then
          echo "The home directory ($dir) of user $user does not exist."
        else
          dirperm=$(ls -ld $dir | cut -f1 -d" ")
          if [ $(echo $dirperm | cut -c5) != "-" ]; then
            echo "Group Read permission set on the home directory ($dir) of user $user"
          fi
          if [ $(echo $dirperm | cut -c6) != "-" ]; then
            echo "Group Write permission set on the home directory ($dir) of user $user"
          fi
          if [ $(echo $dirperm | cut -c7) != "-" ]; then
            echo "Group Execute permission set on the home directory ($dir) of user $user"
          fi
          if [ $(echo $dirperm | cut -c8) != "-" ]; then
            echo "Other Read permission set on the home directory ($dir) of user $user"
          fi
          if [ $(echo $dirperm | cut -c9) != "-" ]; then
            echo "Other Write permission set on the home directory ($dir) of user $user"
          fi
          if [ $(echo $dirperm | cut -c10) != "-" ]; then
            echo "Other Execute permission set on the home directory ($dir) of user $user"
          fi
        fi
      done
  
  - name: 使用者家目錄擁有者(TWGCB-01-008-0080, TWGCB-01-012-0080)
    shell: |
      #!/bin/bash
      grep -E -v '^(halt|sync|shutdown)' /etc/passwd | awk -F: '($7 != "/sbin/nologin" && $7 != "/bin/false") { print $1 " " $6 }' | while read user dir; do
        if [ ! -d "$dir" ]; then
          echo "The home directory ($dir) of user $user does not exist."
        else
          owner=$(stat -L -c "%U" "$dir")
          if [ "$owner" != "$user" ]; then
        echo "The home directory ($dir) of user $user is owned by $owner."
        fi
      fi
      done

  - name: 使用者家目錄擁有群組(TWGCB-01-008-0081, TWGCB-01-012-0081)
    shell: |
      #!/bin/bash
      grep -E -v '^(halt|sync|shutdown)' /etc/passwd | awk -F: '($7 != "/sbin/nologin" && $7 != "/bin/false") { print $1 " " $4 " " $6 }' | while read user gid dir; do
        if [ ! -d "$dir" ]; then
          echo "The home directory ($dir) of user $user does not exist."
        else
          owner=$(stat -L -c "%g" "$dir")
          if [ "$owner" != "$gid" ]; then
        echo "The home directory ($dir) of group $gid is owned by group $owner."
        fi
      fi
      done

  - name: 使用者家目錄之「.」檔案權限(TWGCB-01-008-0082, TWGCB-01-012-0082)
    shell: |
      #!/bin/bash
      grep -E -v '^(halt|sync|shutdown)' /etc/passwd | awk -F: '($7 != "/sbin/nologin" && $7 != "/bin/false") { print $1 " " $6 }' | while read user dir; do
        if [ ! -d "$dir" ]; then
          echo "The home directory ($dir) of user $user does not exist."
        else
          for file in $dir/.[A-Za-z0-9]*; do
            if [ ! -h "$file" -a -f "$file" ]; then
              fileperm=$(ls -ld $file | cut -f1 -d" ")
              if [ $(echo $fileperm | cut -c6) != "-" ]; then
                echo "Group Write permission set on file $file"
              fi
              if [ $(echo $fileperm | cut -c9) != "-" ]; then
                echo "Other Write permission set on file $file"
              fi
            fi
          done
        fi
      done
  
  - name: 使用者家目錄之「.forward」檔案(TWGCB-01-008-0083, TWGCB-01-012-0083)
    shell: |
      #!/bin/bash
      grep -E -v '^(root|halt|sync|shutdown)' /etc/passwd | awk -F: '($7 != "/sbin/nologin" && $7 != "/bin/false") { print $1 " " $6 }' | while read user dir; do
        if [ ! -d "$dir" ]; then
          echo "The home directory ($dir) of user $user does not exist."
        else
          if [ ! -h "$dir/.forward" -a -f "$dir/.forward" ]; then
            echo ".forward file $dir/.forward exists"
          fi
        fi
      done

  - name: 使用者家目錄之「.netrc」檔案(TWGCB-01-008-0084, TWGCB-01-012-0084)
    shell: |
      #!/bin/bash
      grep -E -v '^(root|halt|sync|shutdown)' /etc/passwd | awk -F: '($7 != "/sbin/nologin" && $7 != "/bin/false") { print $1 " " $6 }' | while read user dir; do
        if [ ! -d "$dir" ]; then
          echo "The home directory ($dir) of user $user does not exist."
        else
          if [ ! -h "$dir/.netrc" -a -f "$dir/.netrc" ]; then
            echo ".netrc file $dir/.netrc exists"
          fi
        fi
      done

  - name: 使用者家目錄之「.rhosts」檔案(TWGCB-01-008-0085, TWGCB-01-012-0085)
    shell: |
      #!/bin/bash
      grep -E -v '^(root|halt|sync|shutdown)' /etc/passwd | awk -F: '($7 != "/sbin/nologin" && $7 != "/bin/false") { print $1 " " $6 }' | while read user dir; do
        if [ ! -d "$dir" ]; then
          echo "The home directory ($dir) of user $user does not exist."
        else
          for file in $dir/.rhosts; do
            if [ ! -h "$file" -a -f "$file" ]; then
              echo ".rhosts file in $dir"
            fi
          done
        fi
      done
  - name: 檢查/etc/passwd檔案設定之群組(TWGCB-01-008-0086, TWGCB-01-012-0086)
    shell: |
      #!/bin/bash
      for i in $(cut -s -d: -f4 /etc/passwd | sort -u ); do
        grep -q -P "^.*?:[^:]*:$i:" /etc/group
        if [ $? -ne 0 ]; then
          echo "Group $i is referenced by /etc/passwd but does not exist in /etc/group"
        fi
      done
  - name: 唯一之UID(TWGCB-01-008-0087, TWGCB-01-012-0087)
    shell: |
      #!/bin/bash
      cut -f3 -d":" /etc/passwd | sort -n | uniq -c | while read x ; do
        [ -z "$x" ] && break
        set - $x
        if [ $1 -gt 1 ]; then
          users=$(awk -F: '($3 == n) { print $1 }' n=$2 /etc/passwd | xargs)
          echo "Duplicate UID ($2): $users"
        fi
      done
  - name: 唯一之GID(TWGCB-01-008-0088, TWGCB-01-012-0088)
    shell: |
      #!/bin/bash
      cut -d: -f3 /etc/group | sort | uniq -d | while read x ; do
        echo "Duplicate GID ($x) in /etc/group"
      done
  - name: 唯一之使用者帳號名稱(TWGCB-01-008-0089, TWGCB-01-012-0089)
    shell: |
      #!/bin/bash
      cut -d: -f1 /etc/passwd | sort | uniq -d | while read x
      do echo "Duplicate login name ${x} in /etc/passwd"
      done
  - name: 唯一之群組名稱(TWGCB-01-008-0090, TWGCB-01-012-0090)
    shell: |
      #!/bin/bash
      cut -d: -f1 /etc/group | sort | uniq -d | while read x
      do echo "Duplicate group name ${x} in /etc/group"
      done
