# 系統校時

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: ntp case chrony
  when: "'chrony' in ansible_facts.packages"
  block:

    #################### execute in RedHat older 8 ####################

  - name: execute in RedHat older 8
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version | int >= 8
    block:
    - name: /etc/chrony.conf
      template:
        owner: root
        group: root
        mode: 0644
        dest: /etc/chrony.conf
        src: "{{chrony_conf}}"