#################### execute in RedHat older 8 ####################
- name: RedHat Base version 8
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version | int >= 8
  block:
  - name: execute command
    command: "{{ item }}"
    with_items:
    - grub2-mkconfig -o "$(dirname "$(find /boot -type f \( -name 'grubenv' -o -name 'grub.conf' -o -name 'grub.cfg' \) -exec grep -Pl '^\h*(kernelopts=|linux|kernel)' {} \;)")/grub.cfg" # TWGCB-01-008-0186
    
  - name: /etc/crontab
    file:
      path: /etc/crontab
      owner: root  # TWGCB-01-008-0193
      group: root  # TWGCB-01-008-0193
      mode: '0600' # TWGCB-01-008-0194
  - name: /etc/cron.hourly
    file:
      path: /etc/cron.hourly
      owner: root  # TWGCB-01-008-0195
      group: root  # TWGCB-01-008-0195
      mode: '0700' # TWGCB-01-008-0196
  - name: /etc/cron.daily
    file:
      path: /etc/cron.daily
      owner: root  # TWGCB-01-008-0197
      group: root  # TWGCB-01-008-0197
      mode: '0700' # TWGCB-01-008-0198
  - name: /etc/cron.weekly
    file:
      path: /etc/cron.weekly
      owner: root  # TWGCB-01-008-0199
      group: root  # TWGCB-01-008-0199
      mode: '0700' # TWGCB-01-008-0200
  - name: /etc/cron.monthly
    file:
      path: /etc/cron.monthly
      owner: root  # TWGCB-01-008-0201
      group: root  # TWGCB-01-008-0201
      mode: '0700' # TWGCB-01-008-0202
  - name: /etc/cron.d
    file:
      path: /etc/cron.d
      state: directory
      owner: root  # TWGCB-01-008-0203
      group: root  # TWGCB-01-008-0203
      mode: '0700' # TWGCB-01-008-0204


