#################### execute in RedHat older 8 ####################
- name: RedHat Base version 8
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version | int >= 8
  block:
  - name: execute command
    command: "{{ item }}"
    with_items: 
    - grub2-mkconfig -o "$(dirname "$(find /boot -type f \( -name 'grubenv' -o -name 'grub.conf' -o -name 'grub.cfg' \) -exec grep -Pl '^\h*(kernelopts=|linux|kernel)' {} \;)")/grub.cfg" # TWGCB-01-008-0134,TWGCB-01-008-0135
  - name: /etc/messages
    file:
      path: /etc/messages
      owner: root  # TWGCB-01-008-0178
      group: root  # TWGCB-01-008-0178
  - name: /var/log
    file:
      path: /var/log
      state: directory
      owner: root  # TWGCB-01-008-0179
      group: root  # TWGCB-01-008-0179
