#################### execute in RedHat older 8 ####################

- name: execute in RedHat older 8
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version | int >= 8
  block:

  - name: upload blacklist /etc/modprobe.d/cramfs.conf
    template:
      owner: root
      group: root
      mode: 0644
      dest: /etc/modprobe.d/cramfs.conf
      src: "{{cramfs_conf}}"

  - name: upload blacklist /etc/modprobe.d/squashfs.conf
    template:
      owner: root
      group: root
      mode: 0644
      dest: /etc/modprobe.d/squashfs.conf
      src: "{{squashfs_conf}}"

  - name: upload blacklist /etc/modprobe.d/udf.conf
    template:
      owner: root
      group: root
      mode: 0644
      dest: /etc/modprobe.d/udf.conf
      src: "{{udf_conf}}"

  - name: /etc/modprobe.d/usb-storage.conf
    template:
        owner: root
        group: root
        mode: 0644
        dest: /etc/modprobe.d/usb-storage.conf
        src: "{{usb_storage_conf}}"

  - name: /etc/security/limits.conf TWGCB_008
    template:
      owner: root
      group: root
      mode: 0644
      dest: /etc/security/limits.d/gcb.conf
      src: "{{ TWGCB_008_limits_gcb_conf }}"

  - name: /etc/sysctl.d/gcb.conf
    template:
      owner: root
      group: root
      mode: 0644
      dest: /etc/sysctl.d/gcb.conf
      src: "{{ etc_sysctl_redhat8_1 }}"

  - name: /etc/sysctl.d/50-coredump.conf
    template:
      owner: root
      group: root
      mode: 0644
      dest: /etc/sysctl.d/50-coredump.conf
      src: "{{ etc_sysctl_redhat8_2 }}"
