- name: /etc/passwd
  file:
    path: /etc/passwd
    owner: root  # TWGCB-01-008-0045,TWGCB-01-003-0041
    group: root  # TWGCB-01-008-0045,TWGCB-01-003-0042
    mode: '0644' # TWGCB-01-008-0046,TWGCB-01-003-0040

- name: /etc/shadow
  file:
    path: /etc/shadow
    owner: root  # TWGCB-01-008-0047,TWGCB-01-003-0035
    group: root  # TWGCB-01-008-0047,TWGCB-01-003-0036
    mode: '0000' # TWGCB-01-008-0048,TWGCB-01-003-0034

- name: /etc/group
  file:
    path: /etc/group
    owner: root  # TWGCB-01-008-0049,TWGCB-01-003-0038
    group: root  # TWGCB-01-008-0049,TWGCB-01-003-0039
    mode: '0644' # TWGCB-01-008-0050,TWGCB-01-003-0037

- name: /etc/gshadow
  file:
    path: /etc/gshadow
    owner: root  # TWGCB-01-008-0051,TWGCB-01-003-0032
    group: root  # TWGCB-01-008-0051,TWGCB-01-003-0033
    mode: '0000' # TWGCB-01-008-0052,TWGCB-01-003-0031

#################### execute in RedHat 6 ####################

# - name: execute in RedHat 6
#   when: ansible_os_family == "RedHat" and ansible_distribution_major_version in ["6"]
#   block:

#################### execute in RedHat 7 ####################

- name: execute in RedHat 7
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version in ["7"]
  block:
  - name: /etc/sysctl.conf RedHat7
    template:
      owner: root
      group: root
      mode: 0644
      dest: /etc/sysctl.conf
      src: "{{ etc_sysctl_redhat7_conf }}"

#################### execute in RedHat 5 6 ####################

- name: execute in RedHat 5 6
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version in ["5","6"]
  block:
  - name: /etc/sysctl.conf RedHat6
    template:
      owner: root
      group: root
      mode: 0644
      dest: /etc/sysctl.conf
      src: "{{ etc_sysctl_redhat6_conf }}"

#################### execute in RedHat 5 6 7 ####################

- name: execute in RedHat 5 6 7
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version in ["5","6","7"]
  block:
  - name: /etc/security/limits.conf TWGCB_003
    template:
      owner: root
      group: root
      mode: 0644
      dest: /etc/security/limits.d/gcb.conf
      src: "{{ TWGCB_003_limits_gcb_conf }}"

  - name: /etc/security/console.perms
    template:
      owner: root
      group: root
      mode: 0644
      dest: /etc/security/console.perms
      src: "{{ console_perms }}"



#################### execute in RedHat older 8 ####################

- name: execute in RedHat older 8
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version | int >= 8
  block:

  - name: /etc/passwd-
    file:
      path: /etc/passwd-
      owner: root  # TWGCB-01-008-0053
      group: root  # TWGCB-01-008-0053
      mode: '0000' # TWGCB-01-008-0054

  - name: TWGCB-01-008-0055,TWGCB-01-008-0056 /etc/shadow-
    file:
      path: /etc/shadow-
      owner: root  # TWGCB-01-008-0055
      group: root  # TWGCB-01-008-0055
      mode: '0000' # TWGCB-01-008-0056

  - name: /etc/group-
    file:
      path: /etc/group-
      owner: root  # TWGCB-01-008-0057
      group: root  # TWGCB-01-008-0057
      mode: '0644' # TWGCB-01-008-0058

  - name: /etc/gshadow-
    file:
      path: /etc/gshadow-
      owner: root  # TWGCB-01-008-0059
      group: root  # TWGCB-01-008-0059
      mode: '0000' # TWGCB-01-008-0060

  - name: /etc/security/limits.conf TWGCB_008
    template:
      owner: root
      group: root
      mode: 0644
      dest: /etc/security/limits.d/gcb.conf
      src: "{{ TWGCB_008_limits_gcb_conf }}"


