---
  - include_tasks: TWGCB-install-package.yml    # 安裝 packages
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-removed-package.yml    # 移除 packages
    when: playbook_action in gcb_action
    
  - include_tasks: TWGCB-base-check-disable.yml    # disable 服務 
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-base-check-enable.yml     # enable 服務 
    when: playbook_action in gcb_action
    
  - include_tasks: TWGCB-kernel-net.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0036.yml    # 執行一次就好
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0001.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0002.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0003.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0004.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0029.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0031.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0032.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0034.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0035.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0037.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0041.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0042.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0119.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0120.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0121.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0123.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0126.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0127.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0128.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0129.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0145.yml
    when: playbook_action in gcb_action

  - include_tasks: TWGCB-01-008-0146.yml # 新增的部分
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0147.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0148.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0149.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0150.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0151.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0152.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0153.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0154.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0155.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0156.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0157.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0158.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0159.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0160.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0161.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0162.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0163.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0164.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0165.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0166.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0167.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0168.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0169.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0170.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0171.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0172.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0173.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0176.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0177.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0180.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0181.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0182.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0207.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0210.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0211.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0212.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0213.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0214.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0215.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0216.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0217.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0218.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-01-008-0219.yml
    when: playbook_action in gcb_action

  - include_tasks: TWGCB-audit.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-rsyslog.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-base-execute.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-selinux.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-boot.yml
    when: playbook_action in gcb_action
    
  - include_tasks: TWGCB-base-check-auto.yml       #查詢後自動執行相關指令
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-base-crontab.yml
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-base-check-alert-1.yml    # 有出現值   要跳出警告
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-base-check-alert-0.yml    # 沒有出現值 要跳出警告
    when: playbook_action in gcb_action
  - include_tasks: TWGCB-account.yml
    when: playbook_action in gcb_action
    