---
- name: TWGCB-01-008-0159
  become: true
  shell: |
    [ ! -f /etc/audit/rules.d/audit.rules ] && touch /etc/audit/rules.d/audit.rules
    grep -E '\-a always,exit \-F arch=b64 \-S unlink \-S unlinkat \-S rename \-S renameat \-S rmdir \-F auid>=1000 \-F auid!=4294967295 \-k delete' /etc/audit/rules.d/audit.rules ; retval=$?
    [ $retval -ne 0 ] && echo \-a always,exit \-F arch=b64 \-S unlink \-S unlinkat \-S rename \-S renameat \-S rmdir \-F auid\>=1000 \-F auid!=4294967295 \-k delete >> /etc/audit/rules.d/audit.rules
    grep -E '\-a always,exit \-F arch=b32 \-S unlink \-S unlinkat \-S rename \-S renameat \-S rmdir \-F auid>=1000 \-F auid!=4294967295 \-k delete' /etc/audit/rules.d/audit.rules ; retval=$?
    [ $retval -ne 0 ] && echo \-a always,exit \-F arch=b32 \-S unlink \-S unlinkat \-S rename \-S renameat \-S rmdir \-F auid\>=1000 \-F auid!=4294967295 \-k delete >> /etc/audit/rules.d/audit.rules
    augenrules --load > /dev/null 2>&1
  args:
    executable: /bin/bash
  ignore_errors: true
  