---
- name: TWGCB-base-check-enable Rocky
  become: true
  service:
    enabled: yes
    state: started
    name: "{{ item }}"
  with_items:
    "{{ enable_packages }}"
  when: ansible_distribution == "Rocky" 

- name: TWGCB-base-check-enable CentOS-6
  become: true
  service:
    enabled: yes
    state: started
    name: "{{ item }}"
  with_items:
    "{{ enable_packages }}"
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"

- name: TWGCB-base-check-enable CentOS-7
  become: true
  systemd:
    enabled: yes
    state: started
    name: "{{ item }}"
  with_items:
    "{{ enable_packages }}"
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: TWGCB-base-check-enable CentOS-8
  become: true
  systemd:
    enabled: yes
    state: started
    name: "{{ item }}"
  with_items:
    "{{ enable_packages }}"
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "8"

- name: TWGCB-base-check-enable CentOS-9
  become: true
  systemd:
    enabled: yes
    state: started
    name: "{{ item }}"
  with_items:
    "{{ enable_packages }}"
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "9"

- name: TWGCB-base-check-enable OracleLinux-6
  become: true
  systemd:
    enabled: yes
    state: started
    name: "{{ item }}"
  with_items:
    "{{ enable_packages }}"
  when: ansible_distribution == "OracleLinux" and ansible_distribution_major_version == "6"

- name: TWGCB-base-check-enable OracleLinux-7
  become: true
  service:
    enabled: yes
    state: started
    name: "{{ item }}"
  with_items:
    "{{ enable_packages }}"
  when: ansible_distribution == "OracleLinux" and ansible_distribution_major_version == "7"

- name: TWGCB-base-check-enable OracleLinux-8
  become: true
  systemd:
    enabled: yes
    state: started
    name: "{{ item }}"
  with_items:
    "{{ enable_packages }}"
  when: ansible_distribution == "OracleLinux" and ansible_distribution_major_version == "8"

- name: TWGCB-base-check-enable OracleLinux-9
  become: true
  systemd:
    enabled: yes
    state: started
    name: "{{ item }}"
  with_items:
    "{{ enable_packages }}"
  when: ansible_distribution == "OracleLinux" and ansible_distribution_major_version == "9"
