---
- name: TWGCB-01-008-0154
  become: true
  shell: |
    [ ! -f /etc/audit/rules.d/audit.rules ] && touch /etc/audit/rules.d/audit.rules
    grep -E '\-a always,exit \-F arch=b64 \-S chmod \-S fchmod \-S fchmodat \-F auid>=1000 \-F auid!=4294967295 \-k perm_mod' /etc/audit/rules.d/audit.rules ; retval=$?
    [ $retval -ne 0 ] && echo -a always,exit -F arch=b64 -S chmod -S fchmod -S fchmodat -F auid\>=1000 -F auid!=4294967295 -k perm_mod >> /etc/audit/rules.d/audit.rules
    grep -E '\-a always,exit \-F arch=b32 -S chmod \-S fchmod \-S fchmodat \-F auid>=1000 \-F auid!=4294967295 \-k perm_mod' /etc/audit/rules.d/audit.rules ; retval=$?
    [ $retval -ne 0 ] && echo -a always,exit -F arch=b32 -S chmod -S fchmod -S fchmodat -F auid\>=1000 -F auid!=4294967295 -k perm_mod >> /etc/audit/rules.d/audit.rules
    grep -E '\-a always,exit \-F arch=b64 \-S chown \-S fchown \-S fchownat \-S lchown \-F auid>=1000 \-F auid!=4294967295 \-k perm_mod' /etc/audit/rules.d/audit.rules ; retval=$?
    [ $retval -ne 0 ] && echo -a always,exit -F arch=b64 -S chown -S fchown -S fchownat -S lchown -F auid\>=1000 -F auid!=4294967295 -k perm_mod >> /etc/audit/rules.d/audit.rules
    grep -E '\-a always,exit \-F arch=b32 \-S chown \-S fchown \-S fchownat \-S lchown \-F auid>=1000 \-F auid!=4294967295 \-k perm_mod' /etc/audit/rules.d/audit.rules ; retval=$?
    [ $retval -ne 0 ] && echo -a always,exit -F arch=b32 -S chown -S fchown -S fchownat -S lchown -F auid\>=1000 -F auid!=4294967295 -k perm_mod >> /etc/audit/rules.d/audit.rules
    grep -E '\-a always,exit \-F arch=b64 \-S setxattr \-S lsetxattr \-S fsetxattr \-S removexattr \-S lremovexattr \-S fremovexattr \-F auid>=1000 \-F auid!=4294967295 \-k perm_mod' /etc/audit/rules.d/audit.rules ; retval=$?
    [ $retval -ne 0 ] && echo -a always,exit -F arch=b64 -S setxattr -S lsetxattr -S fsetxattr -S removexattr -S lremovexattr -S fremovexattr -F auid\>=1000 -F auid!=4294967295 -k perm_mod >> /etc/audit/rules.d/audit.rules
    grep -E '\-a always,exit \-F arch=b32 \-S setxattr \-S lsetxattr \-S fsetxattr \-S removexattr \-S lremovexattr \-S fremovexattr \-F auid\>=1000 \-F auid!=4294967295 \-k perm_mod' /etc/audit/rules.d/audit.rules ; retval=$?
    [ $retval -ne 0 ] && echo -a always,exit -F arch=b32 -S setxattr -S lsetxattr -S fsetxattr -S removexattr -S lremovexattr -S fremovexattr -F auid\>=1000 -F auid!=4294967295 -k perm_mod >> /etc/audit/rules.d/audit.rules
    augenrules --load > /dev/null 2>&1
  args:
    executable: /bin/bash
  ignore_errors: true
  