---
- name: TWGCB-01-008-0147
  become: true
  shell: |
    if [ -f /etc/audit/auditd.conf ];then
    sed -ri 's/^\s*(max_log_file_action\s*)(=)(\s*\S+\b).*$/# *REMOVED* \1/' /etc/audit/auditd.conf
    echo max_log_file_action = keep_logs >> /etc/audit/auditd.conf
    fi
  args:
    executable: /bin/bash
  ignore_errors: true
  