---
- name: TWGCB-01-008-0145
  become: true
  shell: |
    file='/etc/aide.conf'
    if [ -f $file ];then
    str=`echo {{ item }} | awk '{print $1}'`
    sed -i $file -e "s|^\s*$str.*||"
    echo {{item}} >> $file
    fi
  args:
    executable: /bin/bash
  ignore_errors: true
  loop:
    - /usr/sbin/auditctl p+i+n+u+g+s+b+acl+xattrs+sha512
    - /usr/sbin/auditd p+i+n+u+g+s+b+acl+xattrs+sha512
    - /usr/sbin/ausearch p+i+n+u+g+s+b+acl+xattrs+sha512
    - /usr/sbin/aureport p+i+n+u+g+s+b+acl+xattrs+sha512
    - /usr/sbin/autrace p+i+n+u+g+s+b+acl+xattrs+sha512
    - /usr/sbin/audisp-remote p+i+n+u+g+s+b+acl+xattrs+sha512
    - /usr/sbin/audisp-syslog p+i+n+u+g+s+b+acl+xattrs+sha512
    - /usr/sbin/augenrules p+i+n+u+g+s+b+acl+xattrs+sha512
    