- name: TWGCB-01-008-0042 TWGCB-01-008-0042 TWGCB-01-008-0232 push /etc/security/limits.d/gcb.conf
  become: true
  copy:
    src: files/{{ansible_distribution}}/{{ansible_distribution_major_version}}/etc/security/limits.d/gcb.conf
    dest: /etc/security/limits.d
    owner: root
    group: root
    mode: 0644

- name: TWGCB-01-008-0042 push /etc/sysctl.d/gcb.conf
  become: true
  copy:
    src: files/{{ansible_distribution}}/{{ansible_distribution_major_version}}/etc/sysctl.d/gcb.conf
    dest: /etc/sysctl.d
    owner: root
    group: root
    mode: 0644

- name: TWGCB-01-008-0042 push /etc/systemd/coredump.conf
  become: true
  copy:
    src: files/{{ansible_distribution}}/{{ansible_distribution_major_version}}/etc/systemd/coredump.conf
    dest: /etc/systemd
    owner: root
    group: root
    mode: 0644

- name: TWGCB-kernel command
  become: true
  command: "{{ item }}"
  with_items: 
    - sysctl -w fs.suid_dumpable=0 # TWGCB-01-008-0042
    - sysctl -w kernel.randomize_va_space=2 # TWGCB-01-008-0043

- name: TWGCB-net command
  become: true
  ignore_errors: true
  shell: |
    sysctl -w {{ item }}
    [ ! -f /etc/sysctl.d/60-netipv4_sysctl.conf ] && touch /etc/sysctl.d/60-netipv4_sysctl.conf
    str=`echo {{ item }} |sed 's|=.*||'`
    sed -i /etc/sysctl.d/60-netipv4_sysctl.conf -e "s|^\s*$str\s*=.*||"
    echo {{ item }} >> /etc/sysctl.d/60-netipv4_sysctl.conf
  with_items:
    - net.ipv4.ip_forward=0 # TWGCB-01-008-0108 1
    - net.ipv6.conf.all.forwarding=0 # TWGCB-01-008-0108 2
    - net.ipv4.conf.all.send_redirects=0 # TWGCB-01-008-0109
    - net.ipv4.conf.default.send_redirects=0 # TWGCB-01-008-0110
    - net.ipv4.conf.all.accept_source_route=0 # TWGCB-01-008-0111 1
    - net.ipv6.conf.all.accept_source_route=0 # TWGCB-01-008-0111 2
    - net.ipv4.conf.default.accept_source_route=0 # TWGCB-01-008-0112 1
    - net.ipv6.conf.default.accept_source_route=0 # TWGCB-01-008-0112 2
    - net.ipv4.conf.all.accept_redirects=0 # TWGCB-01-008-0113 1
    - net.ipv6.conf.all.accept_redirects=0 # TWGCB-01-008-0113 2
    - net.ipv4.conf.default.accept_redirects=0 # TWGCB-01-008-0114 1
    - net.ipv6.conf.default.accept_redirects=0 # TWGCB-01-008-0114 2
    - net.ipv4.conf.all.secure_redirects=0 # TWGCB-01-008-0115
    - net.ipv4.conf.default.secure_redirects=0 # TWGCB-01-008-0116
    - net.ipv4.conf.all.log_martians=1 # TWGCB-01-008-0117
    - net.ipv4.conf.default.log_martians=1 # TWGCB-01-008-0118
    - net.ipv4.conf.default.rp_filter=1 # TWGCB-01-008-0122
    - net.ipv6.conf.all.accept_ra=0 # TWGCB-01-008-0124
    - net.ipv6.conf.default.accept_ra=0 # TWGCB-01-008-0125
    
- name: flush net
  become: true
  command: "{{ item }}"
  with_items:
    - sysctl -w net.ipv4.route.flush=1
    - sysctl -w net.ipv6.route.flush=1

- name: TWGCB-kernel command
  become: true
  command: "{{ item }}"
  with_items: 
    - systemctl daemon-reload # TWGCB-01-008-0042
    
- name: TWGCB-01-008-0042 push /etc/systemd/coredump.conf
  become: true
  copy:
    src: files/{{ansible_distribution}}/{{ansible_distribution_major_version}}/etc/systemd/coredump.conf
    dest: /etc/systemd
    owner: root
    group: root
    mode: 0644
