---
- name: TWGCB-01-008-0035 /etc/sudoers/default_log_file
  become: true
  copy:
    src: files/{{ansible_distribution}}/{{ansible_distribution_major_version}}/etc/sudoers.d/default_log_file
    dest: /etc/sudoers.d
    owner: root
    group: root
    mode: 0440
