---
- name: TWGCB-01-008-0214
  become: true
  shell: |
    [ -f /etc/security/pwquality.conf ] && retval=0
    [ $retval -eq 0 ] && grep -E "^\s*lcredit\s*=\s*-1" /etc/security/pwquality.conf ; retval=$?
    [ $retval -ne 0 ] && echo lcredit = -1 >> /etc/security/pwquality.conf 
  args:
    executable: /bin/bash
  ignore_errors: true
  