---
- name: TWGCB-01-008-0161 
  become: true
  shell: |
    [ ! -f /etc/audit/rules.d/actions.rules ] && touch /etc/audit/rules.d/actions.rules
    chmod g-rwx,o-rwx /etc/audit/rules.d/actions.rules
  args:
    executable: /bin/bash
  ignore_errors: true
  
- name: TWGCB-01-008-0161
  block:
    - name: TWGCB-01-008-0161 check
      become: true
      shell: |
        value=`grep -r logfile /etc/sudoers*`
      register: command_output
      
  rescue:
    - name: TWGCB-01-008-0161 add 1
      become: true
      ignore_errors: true
      shell: |
        grep -r logfile /etc/sudoers* | sed -e 's/.*logfile=//;s/,? .*//' | xargs -l -I FILENAME echo -w FILENAME -p wa -k actions 2>/dev/null >> /etc/audit/rules.d/actions.rules
      register: command_output

- name: TWGCB-01-008-0161
  become: true
  shell: augenrules --load > /dev/null 2>&1
  args:
    executable: /bin/bash
  ignore_errors: true
  