---
- name: TWGCB-01-008-0219
  become: true
  shell: |
    [ -f /etc/security/pwquality.conf ] && retval=0
    [ $retval -eq 0 ] && grep -E "^\s*dictcheck\s*=\s*1" /etc/security/pwquality.conf ; retval=$?
    [ $retval -ne 0 ] && echo dictcheck = 1 >> /etc/security/pwquality.conf 
  args:
    executable: /bin/bash
  ignore_errors: true
  