---
- name: TWGCB-01-008-0032 push /etc/dnf/dnf.conf
  become: true
  copy:
    src: files/{{ansible_distribution}}/{{ansible_distribution_major_version}}/etc/dnf/dnf.conf
    dest: /etc/dnf
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution == "OracleLinux" and ansible_distribution_major_version == "9"

- name: TWGCB-01-008-0032 push /etc/yum.conf and /etc/yum.repos.d/*.repo
  become: true
  shell: |
    sed -i /etc/yum.conf -e 's/^gpgcheck=.*/gpgcheck=1/'
    sed -i /etc/yum.repos.d/*.repo -e 's/^gpgcheck=.*/gpgcheck=1/'
  args:
    executable: /bin/bash
  when: ansible_distribution == "Rocky"

- name: TWGCB-01-008-0032 push /etc/yum.conf
  become: true
  copy:
    src: files/{{ansible_distribution}}/{{ansible_distribution_major_version}}/etc/yum.conf
    dest: /etc
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: TWGCB-01-008-0032 push /etc/yum.repos.d/CentOS-Base.repo
  become: true
  copy:
    src: files/{{ansible_distribution}}/{{ansible_distribution_major_version}}/etc/yum.repos.d/CentOS-Base.repo
    dest: /etc/yum.repos.d
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: TWGCB-01-008-0032 push /etc/yum.repos.d/CentOS-x86_64-kernel.repo
  become: true
  copy:
    src: files/{{ansible_distribution}}/{{ansible_distribution_major_version}}/etc/yum.repos.d/CentOS-x86_64-kernel.repo
    dest: /etc/yum.repos.d
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"