#- name: TWGCB-account push /etc/security/pwquality.conf
  #become: true
  #copy:
    #src: files/{{ansible_distribution}}/{{ansible_distribution_major_version}}/etc/security/pwquality.conf
    #dest: /etc/security
    #owner: root
    #group: root
    #mode: 0644

- name: TWGCB-account push /etc/profile.d/gcb.sh
  become: true
  copy:
    src: files/{{ansible_distribution}}/{{ansible_distribution_major_version}}/etc/profile.d/gcb.sh
    dest: /etc/profile.d
    owner: root
    group: root
    mode: 0644

- name: TWGCB-account push /etc/profile
  become: true
  copy:
    src: files/{{ansible_distribution}}/{{ansible_distribution_major_version}}/etc/profile
    dest: /etc
    owner: root
    group: root
    mode: 0644

- name: TWGCB-01-008-0208
  become: true
  ignore_errors: true
  shell: |
    #!/bin/bash
    source /etc/os-release
    if [ "$VERSION_ID" == "8.3" -o "$VERSION_ID" == "8.2" -o "$VERSION_ID" == "8.1" -o "$VERSION_ID" == "8.0" -o "$VERSION_ID" == "8" ];then
    CP=$(authselect current | awk 'NR == 1 {print $3}' | grep custom/)
    for FN in system-auth password-auth; do
    [[ -n $CP ]] && PTF=/etc/authselect/$CP/$FN || PTF=/etc/authselect/$FN
    [[ -n $(grep -E '^\s*password\s+requisite\s+pam_pwquality.so\s+.*\s+retry=\S+\s*.*$' $PTF) ]] && sed -ri '/pwquality/s/retry=\S+/retry=3/' $PTF || sed -ri 's/^\s*(password\s+requisite\s+pam_pwquality.so\s+)(.*)$/\1\2 retry=3/' $PTF
    done
    authselect apply-changes
    else
    [ ! -f /etc/security/pwquality.conf ] && touch /etc/security/pwquality.conf
    grep "^\s*retry\s*=" /etc/security/pwquality.conf ; retval=$?
    [ $retval -ne 0 ] && echo retry = 3 >> /etc/security/pwquality.conf
    [ $retval -eq 0 ] && sed -i /etc/security/pwquality.conf -e 's/^\s*retry\s*=.*/retry=3/'
    fi
  args:
    executable: /bin/bash

- name: TWGCB-01-008-0209
  become: true
  ignore_errors: true
  shell: |
    #!/bin/bash
    CP=$(authselect current | awk 'NR == 1 {print $3}' | grep custom/)
    for FN in system-auth password-auth; do
    [[ -n $CP ]] && PTF=/etc/authselect/$CP/$FN || PTF=/etc/authselect/$FN
    [[ -z $(grep -E '^\s*password\s+requisite\s+pam_pwquality.so\s+.*enforce_for_root\s*.*$' $PTF) ]] && sed -ri 's/^\s*(password\s+requisite\s+pam_pwquality.so\s+)(.*)$/\1\2 enforce_for_root/' $PTF
    done
    authselect apply-changes
  args:
    executable: /bin/bash
    
- name: TWGCB-01-008-0220
  become: true
  ignore_errors: true
  shell: |
    #!/bin/bash
    source /etc/os-release
    if [ "$VERSION_ID" == "8.1" -o "$VERSION_ID" == "8.0" -o "$VERSION_ID" == "8" ];then
    CP=$(authselect current | awk 'NR == 1 {print $3}' | grep custom/)
    for FN in system-auth password-auth; do
    [[ -n $CP ]] && PTF=/etc/authselect/$CP/$FN || PTF=/etc/authselect/$FN
    [[ -n $(grep -E '^\s*auth\s+required\s+pam_faillock.so\s+.*deny=\S+\s*.*$' $PTF) ]] && sed -ri '/pam_faillock.so/s/deny=\S+/deny=5/g' $PTF || sed -ri 's/^\^\s*(auth\s+required\s+pam_faillock\.so\s+)(.*[^{}])(\{.*\}|)$/\1\2 deny=5 \3/' $PTF
    $PTF
    done
    authselect apply-changes
    else
    [ ! -f /etc/security/faillock.conf ] && touch /etc/security/faillock.conf
    grep "^\s*deny\s*=" /etc/security/faillock.conf ; retval=$?
    [ $retval -ne 0 ] && echo deny = 5 >> /etc/security/faillock.conf
    [ $retval -eq 0 ] && sed -i /etc/security/faillock.conf -e 's/^\s*deny\s*=.*/deny=5/'
    fi
  args:
    executable: /bin/bash

- name: TWGCB-01-008-0221
  become: true
  ignore_errors: true
  shell: |
    #!/bin/bash
    source /etc/os-release
    if [ "$VERSION_ID" == "8.1" -o "$VERSION_ID" == "8.0" -o "$VERSION_ID" == "8" ];then
    CP=$(authselect current | awk 'NR == 1 {print $3}' | grep custom/)
    for FN in system-auth password-auth; do
    [[ -n $CP ]] && PTF=/etc/authselect/$CP/$FN || PTF=/etc/authselect/$FN
    [[ -n $(grep -E '^\s*auth\s+required\s+pam_faillock.so\s+.*unlock_time=\S+\s*.*$' $PTF) ]] && sed -ri '/pam_faillock.so/s/unlock_time=\S+/unlock_time=900/g' $PTF || sed -ri 's/^\s*(auth\s+required\s+pam_faillock\.so\s+)(.*[^{}])(\{.*\}|)$/\1\2 unlock_time=900 \3/' $PTF
    done
    authselect apply-changes
    else
    [ ! -f /etc/security/faillock.conf ] && touch /etc/security/faillock.conf
    grep "^\s*unlock_time\s*=" /etc/security/faillock.conf ; retval=$?
    [ $retval -ne 0 ] && echo unlock_time = 900 >> /etc/security/faillock.conf
    [ $retval -eq 0 ] && sed -i /etc/security/faillock.conf -e 's/^\s*unlock_time\s*=.*/unlock_time=900/'
    fi
  args:
    executable: /bin/bash

- name: TWGCB-01-008-0222
  become: true
  ignore_errors: true
  shell: |
    #!/bin/bash
    CP=$(authselect current | awk 'NR == 1 {print $3}' | grep custom/)
    [[ -n $CP ]] && PTF=/etc/authselect/$CP/system-auth || PTF=/etc/authselect/system-auth
    [[ -n $(grep -E '^\s*password\s+(sufficient\s+pam_unix|requi(red|site)\s+pam_pwhistory).so\s+([^#]+\s+)*remember=\S+\s*.*$' $PTF) ]] && sed -ri 's/^\s*(password\s+(requisite|sufficient)\s+(pam_pwquality\.so|pam_unix\.so)\s+)(.*)(remember=\S+\s*)(.*)$/\1\4 remember=3 \6/' $PTF || sed -ri 's/^\s*(password\s+(requisite|sufficient)\s+(pam_pwquality\.so|pam_unix\.so)\s+)(.*)$/\1\4 remember=3/' $PTF
    authselect apply-changes
  args:
    executable: /bin/bash

- name: TWGCB-account TWGCB-01-008-0223 push /etc/authselect/postlogin
  become: true
  copy:
    src: files/{{ansible_distribution}}/{{ansible_distribution_major_version}}/etc/authselect/postlogin
    dest: /etc/authselect
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution == "OracleLinux" and ansible_distribution_major_version == "9"

- name: TWGCB-account TWGCB-01-008-0223 push /etc/pam.d/postlogin
  become: true
  copy:
    src: files/{{ansible_distribution}}/{{ansible_distribution_major_version}}/etc/pam.d/postlogin
    dest: /etc/pam.d
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution == "Rocky"

- name: TWGCB-account TWGCB-01-008-0223 push /etc/pam.d/postlogin-ac
  become: true
  copy:
    src: files/{{ansible_distribution}}/{{ansible_distribution_major_version}}/etc/pam.d/postlogin-ac
    dest: /etc/pam.d
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: TWGCB-01-008-0224
  become: true
  ignore_errors: true
  shell: |
    #!/bin/bash
    [ -f /etc/libuser.conf ] && retval=0
    [ $retval -eq 0 ] && grep -E "^\s*crypt_style\s*=\s*sha512" /etc/libuser.conf ; retval=$?
    [ $retval -ne 0 ] && echo crypt_style = sha512 >> /etc/libuser.conf 
    [ -f /etc/login.defs ] && retval=0
    [ $retval -eq 0 ] && grep -E "^\s*ENCRYPT_METHOD\s*SHA512" /etc/login.defs ; retval=$?
    [ $retval -ne 0 ] && echo ENCRYPT_METHOD SHA512 >> /etc/login.defs 
    authselect create-profile pwENCY -b sssd --symlink-meta
    authselect select custom/pwENCY with-sudo with-faillock without-nullok
    CP=$(authselect current | awk 'NR == 1 {print $3}' | grep custom/)
    for FN in system-auth password-auth; do
    [[ -n $CP ]] && PTF=/etc/authselect/$CP/$FN || PTF=/etc/authselect/$FN
    [[ -z $(grep -E '^\s*password\s+sufficient\s+pam_unix.so\s+.*sha512\s*.*$' $PTF) ]] && sed -ri 's/^\s*(password\s+sufficient\s+pam_unix.so\s+)(.*)$/\1\2 sha512/' $PTF
    done
    authselect apply-changes
  args:
    executable: /bin/bash

- name: TWGCB-01-008-0225
  become: true
  ignore_errors: true
  shell: |
    #!/bin/bash
    file=/etc/login.defs
    repl="PASS_MIN_DAYS 1"
    str1=`echo $repl|awk '{print $1}'`
    str="^\s*${str1}"
    if [ -f $file ];then
    echo "Search string"
    grep -E "$str" $file ; retval=$?
    if [ $retval -eq 0 ];then
    sed -i $file -e "s|$str.*|$repl|" $file ; retval=$?
    else
    echo "$repl" >> /etc/login.defs
    fi
    else
    echo "$repl" >> /etc/login.defs
    fi
    grep -E "$str" $file
    cmd="chage --mindays 1"
    cat /etc/passwd|awk -F: '{ if ( $3 > 999 && $3 < 65534 ) { print $1 } }'|xargs -l $cmd
  args:
    executable: /bin/bash

- name: TWGCB-01-008-0226
  become: true
  ignore_errors: true
  shell: |
    #!/bin/bash
    file=/etc/login.defs
    repl="PASS_WARN_AGE 14"
    str1=`echo $repl|awk '{print $1}'`
    str="^\s*${str1}"
    if [ -f $file ];then
    echo "Search string"
    grep -E "$str" $file ; retval=$?
    if [ $retval -eq 0 ];then
    sed -i $file -e "s|$str.*|$repl|" $file ; retval=$?
    else
    echo "$repl" >> /etc/login.defs
    fi
    else
    echo "$repl" >> /etc/login.defs
    fi
    grep -E "$str" $file
    cmd="chage --warndays 14"
    cat /etc/passwd|awk -F: '{ if ( $3 > 999 && $3 < 65534 ) { print $1 } }'|xargs -l $cmd
  args:
    executable: /bin/bash

- name: TWGCB-01-008-0227
  become: true
  ignore_errors: true
  shell: |
    #!/bin/bash
    file=/etc/login.defs
    repl="PASS_MAX_DAYS 90"
    str1=`echo $repl|awk '{print $1}'`
    str="^\s*${str1}"
    if [ -f $file ];then
    echo "Search string"
    grep -E "$str" $file ; retval=$?
    if [ $retval -eq 0 ];then
    sed -i $file -e "s|$str.*|$repl|" $file ; retval=$?
    else
    echo "$repl" >> /etc/login.defs
    fi
    else
    echo "$repl" >> /etc/login.defs
    fi
    grep -E "$str" $file
    cmd="chage --maxdays 90"
    cat /etc/passwd|awk -F: '{ if ( $3 > 999 && $3 < 65534 ) { print $1 } }'|xargs -l $cmd
  args:
    executable: /bin/bash

- name: TWGCB-01-008-0228
  become: true
  ignore_errors: true
  shell: |
    #!/bin/bash
    useradd -D -f 30
    cmd="chage --inactive 30"
    cat /etc/passwd|awk -F: '{ if ( $3 > 999 && $3 < 65534 ) { print $1 } }'|xargs -l $cmd
  args:
    executable: /bin/bash

- name: TWGCB-01-008-0229
  become: true
  ignore_errors: true
  shell: |
    #!/bin/bash
    file=/etc/login.defs
    repl="FAIL_DELAY 4"
    echo $repl|grep '=';retval=$?
    if [ $retval -eq 0 ];then
    str1=`echo $repl|awk -F= '{print $1}'`
    str="^\s*${str1}\s*="
    else
    str1=`echo $repl|awk '{print $1}'`
    str="^\s*${str1}"
    fi
    if [ -f $file ];then
    echo "Search string"
    grep -E "$str" $file ; retval=$?
    if [ $retval -eq 0 ];then
    sed -i $file -e "s|$str.*|$repl|" $file ; retval=$?
    else
    echo "$repl" >> /etc/login.defs
    fi
    else
    echo "$repl" >> /etc/login.defs
    fi
    echo "Verify string"
    grep -E "$str" $file
  args:
    executable: /bin/bash

- name: TWGCB-01-008-0230
  become: true
  ignore_errors: true
  shell: |
    #!/bin/bash
    file=/etc/login.defs
    repl="CREATE_HOME yes"
    echo $repl|grep '=';retval=$?
    if [ $retval -eq 0 ];then
    str1=`echo $repl|awk -F= '{print $1}'`
    str="^\s*${str1}\s*="
    else
    str1=`echo $repl|awk '{print $1}'`
    str="^\s*${str1}"
    fi
    if [ -f $file ];then
    echo "Search string"
    grep -E "$str" $file ; retval=$?
    if [ $retval -eq 0 ];then
    sed -i $file -e "s|$str.*|$repl|" $file ; retval=$?
    else
    echo "$repl" >> /etc/login.defs
    fi
    else
    echo "$repl" >> /etc/login.defs
    fi
    echo "Verify string"
    grep -E "$str" $file
  args:
    executable: /bin/bash

- name: TWGCB-01-008-0237 1
  become: true
  ignore_errors: true
  shell: |
    #!/bin/bash
    echo "確認 nologin 非 root 系統帳號"
    awk -F: '($1!="root" && $1!="sync" && $1!="shutdown" && $1!="halt" && $1!~/^\+/ && $3<'"$(awk '/^\s*UID_MIN/{print $2}' /etc/login.defs)"' && $7!="'"$(which nologin)"'" && $7!="/bin/false") {print $1}' /etc/passwd | while read user; do usermod -s $(which nologin) $user; done
    echo "鎖定 nologin 非 root 系統帳號"
    awk -F: '($1!="root" && $1!~/^\+/ && $3<'"$(awk '/^\s*UID_MIN/{print $2}' /etc/login.defs)"') {print $1}' /etc/passwd | xargs -I '{}' passwd -S '{}' | awk '($2!="L" && $2!="LK") {print $1}' | while read user; do usermod -L $user; done
  args:
    executable: /bin/bash

#- name: TWGCB-account push /etc/bashrc
  #become: true
  #copy:
    #src: files/{{ansible_distribution}}/{{ansible_distribution_major_version}}/etc/bashrc
    #dest: /etc
    #owner: root
    #group: root
    #mode: 0644
    
- name: TWGCB-01-008-0238
  become: true
  ignore_errors: true
  shell: |
    #!/bin/bash
    file=/etc/bashrc
    repl='{{item}}'
    echo $repl|grep '=';retval=$?
    if [ $retval -eq 0 ];then
    str1=`echo $repl|awk -F= '{print $1}'`
    str="^\s*${str1}\s*="
    else
    str1=`echo $repl|awk '{print $1}'`
    str="^\s*${str1}"
    fi
    if [ -f $file ];then
    echo "Search string"
    grep -E "$str" $file ; retval=$?
    if [ $retval -eq 0 ];then
    sed -i $file -e "s|$str.*|$repl|" $file ; retval=$?
    else
    echo "$repl" >> $file
    fi
    else
    echo "$repl" >> $file
    fi
    echo "Verify string"
    grep -E "$str" $file
  args:
    executable: /bin/bash
  with_items:
    - TMOUT=900 #TWGCB-01-008-0238
    - umask 027 #TWGCB-01-008-0241

- name: TWGCB-01-008-0242
  become: true
  ignore_errors: true
  shell: |
    #!/bin/bash
    file=/etc/login.defs
    str='umask '
    repl='umask 027'
    gcbtmp=$file.gcbtmp
    if [ -f $file ];then
    grep "$str" $file ;retval=0
    if [ $retval -eq 0 ];then
    echo "remove $str "
    echo "add $str "
    cat $file > $gcbtmp
    sed -i $gcbtmp -e "s|\(.*$str.*\)|# \1|"
    echo "$repl" >> $gcbtmp
    cat $gcbtmp > $file
    rm -f $gcbtmp
    else
    echo "add $str "
    echo $repl >> $file
    fi
    fi
  args:
    executable: /bin/bash

- name: TWGCB-01-008-0240
  become: true
  ignore_errors: true
  command: usermod -g 0 root

- name: TWGCB-01-008-0243
  become: true
  ignore_errors: true
  shell: |
    #!/bin/bash
    file=/etc/pam.d/su
    str='^\s*auth\s*required\s*pam_wheel.so\s*use_uid.*'
    if [ -f $file ];then
    echo "Search string"
    grep -E "$str" $file ; retval=$?
    if [ $retval -eq 0 ];then
    sed -i $file -e "s|$str| |" $file ; retval=$?
    fi
    echo "auth required pam_wheel.so use_uid" >> $file
    echo "Verify string"
    grep -E "$str" $file
    fi
  args:
    executable: /bin/bash
