---
- name: TWGCB-01-008-0173
  become: true
  shell: |
    [ ! -f /etc/audit/rules.d/audit.rules ] && touch /etc/audit/rules.d/audit.rules
    grep -h "^\s*[^#]" /etc/audit/rules.d/*.rules | egrep "(-e 2)|(--loginuid-immutable)" ; retval=$?
    [ $retval -ne 0 ] && echo '-e 2' >> /etc/audit/rules.d/audit.rules
    augenrules --load > /dev/null 2>&1
  args:
    executable: /bin/bash
  ignore_errors: true
  
