---
- name: TWGCB-01-008-0166
  become: true
  shell: |
    [ ! -f /etc/audit/rules.d/audit.rules ] && touch /etc/audit/rules.d/audit.rules
    grep -E '\-a always,exit \-F arch=b32 \-S finit_module \-F auid>=1000 \-F auid!=4294967295 \-k module_chng' /etc/audit/rules.d/audit.rules ; retval=$?
    [ $retval -ne 0 ] && echo \-a always,exit \-F arch=b32 \-S finit_module \-F auid\>=1000 \-F auid!=4294967295 \-k module_chng >> /etc/audit/rules.d/audit.rules
    grep -E '\-a always,exit \-F arch=b64 \-S finit_module \-F auid>=1000 \-F auid!=4294967295 \-k module_chng' /etc/audit/rules.d/audit.rules ; retval=$?
    [ $retval -ne 0 ] && echo \-a always,exit \-F arch=b32 \-S finit_module \-F auid\>=1000 \-F auid!=4294967295 \-k module_chng >> /etc/audit/rules.d/audit.rules
    augenrules --load > /dev/null 2>&1
  args:
    executable: /bin/bash
  ignore_errors: true
  