---
- name: TWGCB-01-008-0216
  become: true
  shell: |
    [ -f /etc/security/pwquality.conf ] && retval=0
    [ $retval -eq 0 ] && grep -E "^\s*difok\s*=\s*3" /etc/security/pwquality.conf ; retval=$?
    [ $retval -ne 0 ] && echo difok = 3 >> /etc/security/pwquality.conf 
  args:
    executable: /bin/bash
  ignore_errors: true
  