---
- name: TWGCB-01-008-0149
  become: true
  shell: |
    [ ! -f /etc/audit/rules.d/audit.rules ] && touch /etc/audit/rules.d/audit.rules
    grep -E '\-w /var/run/faillock/ \-p wa \-k logins' /etc/audit/rules.d/audit.rules ; retval=$?
    [ $retval -ne 0 ] && echo -w /var/run/faillock/ -p wa -k logins >> /etc/audit/rules.d/audit.rules
    grep -E '\-w /var/log/lastlog \-p wa \-k logins' /etc/audit/rules.d/audit.rules ; retval=$?
    [ $retval -ne 0 ] && echo -w /var/log/lastlog -p wa -k logins >> /etc/audit/rules.d/audit.rules
    augenrules --load > /dev/null 2>&1
  args:
    executable: /bin/bash
  ignore_errors: true
  