- name: TWGCB-01-008-0187 TWGCB-01-008-0188 TWGCB-selinux push /etc/selinux/config
  become: true
  copy:
    src: files/{{ansible_distribution}}/{{ansible_distribution_major_version}}/etc/selinux/config
    dest: /etc/selinux
    owner: root
    group: root
    mode: 0640
    