---
- name: TWGCB-01-008-0180
  become: true
  shell: |
    [ -f /etc/systemd/journald.conf ] && retval=0
    [ $retval -eq 0 ] && grep -E "^\s*ForwardToSyslog\s*=\s*yes" /etc/systemd/journald.conf ; retval=$?
    [ $retval -ne 0 ] && echo ForwardToSyslog=yes >> /etc/systemd/journald.conf ; systemctl restart systemd-journald
  args:
    executable: /bin/bash
  ignore_errors: true
  