---
- name: TWGCB-01-008-0158
  become: true
  shell: |
    [ ! -f /etc/audit/rules.d/privileged.rules ] && touch /etc/audit/rules.d/privileged.rules
    chmod g-rwx,o-rwx /etc/audit/rules.d/privileged.rules
  args:
    executable: /bin/bash
  ignore_errors: true

- name: TWGCB-01-008-0158
  block:
    - name: TWGCB-01-008-0158 check
      become: true
      shell: |
        value=`find "/" -xdev \( -perm -4000 -o -perm -2000 \) -type f | head -1 | awk '{print $1 }'`
        grep $value /etc/audit/rules.d/privileged.rules
      register: command_output
      with_items:
        "{{ partition_list }}"
        
  rescue:
    - name: TWGCB-01-008-0158 add
      become: true
      ignore_errors: true
      shell: find "{{ item }}" -xdev \( -perm -4000 -o -perm -2000 \) -type f | awk '{print "-a always,exit -F path=" $1 " -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged" }' >> /etc/audit/rules.d/privileged.rules
      register: command_output
      with_items:
        "{{ partition_list }}"
        
- name: TWGCB-01-008-0158
  become: true
  shell: augenrules --load > /dev/null 2>&1
  args:
    executable: /bin/bash
  ignore_errors: true
  