---
- name: TWGCB-01-008-0173
  become: true
  shell: |
    if [ -f /etc/audit/rules.d/audit.rules ];then
    sed -ri "s/^.*(-e\s*.).*$/# *REMOVED* \1/" /etc/audit/rules.d/audit.rules
    echo '-e 2' >> /etc/audit/rules.d/audit.rules
    augenrules --load > /dev/null 2>&1
  args:
    executable: /bin/bash
  ignore_errors: true
  
