---    
- name: TWGCB-01-008-0093 chrony.conf NTP Server setting
  become: true
  shell: |
    grep -E '^\s*server|^server' /etc/chrony.conf
  args:
    executable: /bin/bash
  ignore_errors: true
  register: command_output

- debug:
    var: command_output.stdout_lines
    
- name: TWGCB-01-008-0107 /etc/dnf/dnf.conf and /etc/yum.conf clean_requirements_on_remove=True
  become: true
  shell: |
    grep -E '^\s*clean_requirements_on_remove' /etc/dnf/dnf.conf |grep -v ^#|grep -Ei '=\s*true'
    grep -E '^\s*clean_requirements_on_remove' /etc/yum.conf |grep -v ^#|grep -Ei '=\s*true'
  args:
    executable: /bin/bash
  ignore_errors: true
  register: command_output

- debug:
    var: command_output.stdout_lines
    