---
- name: TWGCB-01-008-0172
  become: true
  shell: |
    [ ! -f /etc/audit/rules.d/audit.rules ] && touch /etc/audit/rules.d/audit.rules
    grep -E '\-a always,exit \-F arch=b32 \-F auid!=unset \-S execve \-C uid!=euid \-F key=execpriv' /etc/audit/rules.d/audit.rules ; retval=$?
    [ $retval -ne 0 ] && echo \-a always,exit \-F arch=b32 \-F auid!=unset \-S execve \-C uid!=euid \-F key=execpriv >> /etc/audit/rules.d/audit.rules
    grep -E '\-a always,exit \-F arch=b64 \-F auid!=unset \-S execve \-C uid!=euid \-F key=execpriv' /etc/audit/rules.d/audit.rules ; retval=$?
    [ $retval -ne 0 ] && echo \-a always,exit \-F arch=b64 \-F auid!=unset \-S execve \-C uid!=euid \-F key=execpriv >> /etc/audit/rules.d/audit.rules
    grep -E '\-a always,exit \-F arch=b32 \-F auid!=unset \-S execve \-C gid!=egid \-F key=execpriv' /etc/audit/rules.d/audit.rules ; retval=$?
    [ $retval -ne 0 ] && echo \-a always,exit \-F arch=b32 \-F auid!=unset \-S execve \-C gid!=egid \-F key=execpriv >> /etc/audit/rules.d/audit.rules
    grep -E '\-a always,exit \-F arch=b64 \-F auid!=unset \-S execve \-C gid!=egid \-F key=execpriv' /etc/audit/rules.d/audit.rules ; retval=$?
    [ $retval -ne 0 ] && echo \-a always,exit \-F arch=b64 \-F auid!=unset \-S execve \-C gid!=egid \-F key=execpriv >> /etc/audit/rules.d/audit.rules
    augenrules --load > /dev/null 2>&1
  args:
    executable: /bin/bash
  ignore_errors: true
  