---
- name: TWGCB-01-008-0231 1
  become: true
  ignore_errors: true
  shell: |
    #!/bin/bash
    files=`find /etc/sudoers.d/*`
    strs='.*NOPASSWD.*' 
    for file in $files;do
    for str in $strs;do
    if [ -f $file ];then
    echo "Search string"
    grep -E "$str" $file ; retval=$?
    if [ $retval -eq 0 ];then
    sed -ri $file -e "s|($str)|# REMOVE \1|"; retval=$?
    fi
    fi
    done
    done
    #!/bin/bash
    files='/etc/sudoers'
    strs='.*NOPASSWD.*' 
    for file in $files;do
    for str in $strs;do
    if [ -f $file ];then
    echo "Search string"
    grep -E "$str" $file ; retval=$?
    if [ $retval -eq 0 ];then
    sed -ri $file -e "s|($str)|# REMOVE \1|" ; retval=$?
    fi
    fi
    done
    done
    files=`find /etc/sudoers.d/*`
    strs='.*!authenticate.*' 
    for file in $files;do
    for str in $strs;do
    if [ -f $file ];then
    echo "Search string"
    grep -E "$str" $file ; retval=$?
    if [ $retval -eq 0 ];then
    sed -ri $file -e "s|($str)|# REMOVE \1|" ; retval=$?
    fi
    fi
    done
    done
    #!/bin/bash
    files='/etc/sudoers'
    strs='.*!authenticate.*' 
    for file in $files;do
    for str in $strs;do
    if [ -f $file ];then
    echo "Search string"
    grep -E "$str" $file ; retval=$?
    if [ $retval -eq 0 ];then
    sed -ri $file -e "s|($str)|# REMOVE \1|" ; retval=$?
    fi
    fi
    done
    done
    
  args:
    executable: /bin/bash
    
